:- ensure_loaded(p01).
:- ensure_loaded(p02).
:- ensure_loaded(p03).
:- ensure_loaded(p04).
:- ensure_loaded(p05).
:- ensure_loaded(p06).
:- ensure_loaded(p07).
:- ensure_loaded(p08).
:- ensure_loaded(p09).
:- ensure_loaded(p10).
